### ISSUE TITLE
Tomarun_Flluppy_Bird

### ISSUE THREAD

**Issue by Tomarun029831** [sg-TERA/22I-Portal#2]
titel: Fluppy_Bird
comment: [URL](https://drive.google.com/drive/folders/1c_zqtKjaTf1Bg7ibxg266-v_X-5Qryxb?usp=drive_link), Tomarun, アセットの権利、Unityの権利について知らないので拡散はしないでください。

**Comment by sg-tera** [comment]
READMEに書き方を書いたので、このissuesのままでいいですから、コメントを追加してください

**Comment by sg-tera** [comment]
追加しました
